sudo: required
services:
    - docker

before_install:
    - docker build -t rene/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true rene/docker-react npm run test

deploy: 
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-453235089263"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

